name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        go build -v .
        chmod +x gg
        mkdir pub
        cp gg pub

    - name: Test
      env: 
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
      run: |
        export PATH="${PATH}:`pwd`"
        gg sync --token ${TEST_TOKEN}
        echo "test_gist" > test_gist.txt
        ls -lah
        cat test_gist.txt
        chmod 775 test_gist.txt
        gg new --description "test text"  test_gist.txt
        bash tests/functional-tests.sh

    - name: todo-actions
      uses: dtinth/todo-actions@v0.2.0



    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: gg
        path: pub 
